name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests and capture results
        run: ./gradlew test --info
        continue-on-error: true
      - name: Save test results
        if: failure()
        run: ./gradlew test --info > test_results.txt
      - name: Notify on Telegram if tests succeed
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: "All tests passed successfully 🎉"
      - name: Notify on Telegram if tests fail
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: "Some tests failed. Check the logs for more details."
      - name: Send detailed failure report
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: |
            Failed tests:
            ${{ steps.failures.outputs.failed-tests }}
      - name: Prepare detailed test report
        id: failures
        if: failure()
        run: echo "::set-output name=failed-tests::$(grep -E 'FAILED|FAILURE' test_results.txt)"

